### ISSUE TITLE
User unable to see the form.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/webform#2]
I have just installed Webform but it is saying that a user must log-in in order to see and use the form. I have tried setting permissions so that ananonymous user can create new webform content but that hasn't made any difference. Any suggestions?

**Comment by Graham-72** [comment]
Probably need to apply the changes described in https://api.backdropcms.org/node/26870 - 'Converted User roles to CMI ' ? e.g. in includes/webform.pages.inc on line 175

**Comment by Graham-72** [comment]
I have made a PR https://github.com/backdrop-contrib/webform/pull/3 that incorporates changes I have made to get my installation working. It is not yet fully tested and I may have missed something, but it is functional and I am able to use Webform on a live site.

**Comment by Graham-72** [comment]
PR #3 is not solving all the problems, though it does enable webform to be used provided you disable Webform submission access control in Advanced settings. I will persist in trying to find a full solution.

**Comment by biolithic** [comment]
I merged https://github.com/backdrop-contrib/webform/pull/3 to provide a temporary solution and will be looking at this in the next two days.  Thanks!

**Comment by Graham-72** [comment]
I came across this problem again today and found that what I had to do to disable submission access control was to change a value in the webform.settings config file
webform_submission_access_control has to be set to 0 i.e. the line must be
`
"webform_submission_access_control": "0",
`
This is controlled by a setting in the general Webform advanced settings, not the advanced settings for the specific webform.

I have added this comment as an explanation for something that was confusing me, because there are these two separate places for Advanced Settings.

**Comment by bd0bd** [comment]
Hello everyone!

Here is my report.
After installation and setup the form I have this error:

![webform_error](https://cloud.githubusercontent.com/assets/13515302/8904869/c5b43ee8-346b-11e5-82b2-8f22b4876643.gif)

**Comment by bd0bd** [comment]
So many days has left but nobody is gong to fix it (I would do it but I can not).
For now it is a time to go from Backdrop back to Drupal 7 :(

**Comment by docwilmot** [comment]
Sorry, @bd0bd hopefully @Graham-72 can have a look soon. I havent used webform at all so it would be some time before I could get around to figuring out whats going on.

**Comment by Graham-72** [comment]
@bd0bd I will try and help but I am a bit handicapped this week because I am away on holiday and suffering a very inferior internet connection. I have got a working version of Webform on Backdrop but only if submission access control is off (see my note above of 9 days ago) - this means that users do not have to be logged in.

I will check on what code changes I had to make to achieve this and report back here. Are you OK to edit your PHP code or do you need a complete module? Perhaps I should fork a temporary repo you could download and try.

**Comment by bd0bd** [comment]
docwilmot and Graham-72 thank you very much for your responses!
Of cause, I can edit any file including PHP code via FTP. I am not a new with web stuff but I am not familiar enough with programming to do it without your help :)
Thank you!

Sorry, how to make text bold (strong) here? >b<>/b<, >strong<>/strong<

**Comment by docwilmot** [comment]
@Graham-72, I pushed a few changes to Webform which seem to correct access issues (for me at least), hope you dont mind. Didnt want @bd0bd to leave with a bad impression.

@bd0bd can you try this version please? https://github.com/backdrop-contrib/webform/archive/1.x-1.x.zip. You will have to uninstall and re-enable Webfom.

Note I didnt actually see your error when I installed, but I have a suspicion that this may work.

**Comment by bd0bd** [comment]
docwilmot, thank you! The error is fixed. But another on is here after submitting the form:

Notice: Undefined index: complete form in _webform_client_form_validate() (line 2929 of /drop/modules/webform-1.x-1.x/webform.module).

**Comment by docwilmot** [comment]
Not seeing this at all. Anonymous? What fields you got in your form? Maybe its field specific? You on the latest release of Backdrop? And cleared caches?

**Comment by bd0bd** [comment]
Not Anonymous. Logged in.
2 fields: email and textarea.
Backdrop reinstalled today.
Caches cleared.

**Comment by docwilmot** [comment]
Last thing: PHP version?

Adding  `$form_state['complete form'] = array();` just before line 2929 will fix this error, although I still dont know why it happens.

**Comment by bd0bd** [comment]
PHP:  5.4

**Comment by bd0bd** [comment]
Sorry!
NOT 5.4
It is 5.4.43

**Comment by bd0bd** [comment]
Well, now it seems everything is OK and I will stay with Backdrop for now :)
One question - where I can ask Backdrop related questions?
I do not see any forum here on the backdrop.org site or a special section on drupal.org site.

**Comment by Graham-72** [comment]
> > hope you dont mind. Didnt want @bd0bd to leave with a bad impression.

@docwilmot  I'm delighted to start my day by finding you have done this. Many thanks for taking time to look at this.

@bd0bd Glad to hear you are staying with Backdrop. For more general questions you could try http://www.reddit.com/r/backdrop/

**Comment by bd0bd** [comment]
**docwilmot** and **Graham-72** thank you very much!

BTW: When I have got this Webform error then I have contacted several people and companies to help me. One of the company who had its logo here - https://backdropcms.org/ - under the We support Backdrop CMS - has replied me they do not work any more with Backdrop CMS. I think there are many individuals and companies around here who were driven away from Backdrop CMS after they face some minor errors with Webform module or other **important modules**.

Thank you!

**Comment by docwilmot** [comment]
> One question - where I can ask Backdrop related questions?
> I do not see any forum here on the backdrop.org site or a special section on drupal.org site.

@quicksketch @jenlampton 
This is an issue which we really need to address. I have mentioned it [here](https://github.com/backdrop-ops/backdropcms.org/issues/84) and [here](https://www.reddit.com/r/backdrop/comments/33akps/its_backdrop_sociable_enough/), and this very topic was my [first ever post on Backdrop](https://github.com/backdrop-ops/backdropcms.org/issues/18). As noted in the article above, its been mentioned [elsewhere]() and on the [GitHub issue queue](https://github.com/backdrop/backdrop-issues/issues/385) by others.

We need to work on discussion support. As per [the last post](https://github.com/backdrop-ops/backdropcms.org/issues/84) at the very least the Reddit should be given **prominence** on the Backdrop.org front page. Ideally, as @klonos agrees, we should have a forum. 

I believe signing up as a member of something at least gives the impression that you belong there; signing up at the Reddit means you belong to a Reddit. Plus having a Backdrop signup gives us some way of tracking the size of the interest in Backdrop as a community. I concede its been discussed, and resources etc etc. But I suspect its worth the investment.

I think to grow as a community, this must be revisited.

**Comment by bd0bd** [comment]
Support - this is a vital thing and I believe they know about this but probably they have some reasons not to rush with implementing it :)

**docwilmot** the form is invisible for anon users.
In the Permissions section (Home > Administration > Configuration > User accounts) I have checked all the checkboxes but it does not help.

![webform](https://cloud.githubusercontent.com/assets/13515302/9110013/e4c482b4-3c42-11e5-898e-bc42a615ac45.gif)

![permission](https://cloud.githubusercontent.com/assets/13515302/9110062/5380f2f0-3c43-11e5-98fd-dcef17d07029.gif)

**Comment by Graham-72** [comment]
@bd0bd I am very sorry you are still having problems. Have you spotted what I wrote above 10 days ago?

> > What I had to do to disable submission access control was to change a value in the webform.settings config file
> > webform_submission_access_control has to be set to 0 i.e. the line must be
> > "webform_submission_access_control": "0",
> > This is controlled by a setting in the general Webform advanced settings, not the advanced settings for the specific webform.

Have you tried disabling submission access control in wbeform - not in the permissions that you have just shown?

I don't yet know how much @docwilmot 's changes have put right, but I have a version that works provided submission access control is not enabled, and I will gladly share this with you if it meets your immediate need.

It will take a little longer to get a version which provides for submission access control and right now I'm afraid I have other priorities. Very sorry about this.

**Comment by bd0bd** [comment]
**Graham-72**, I am sorry for my inattention to the above posts :)
Yes, now the form is visible after I have disabled submission access control in Webform.
Thank you!

**Comment by docwilmot** [comment]
Strange again, its fine for me for anon. You sure you checked anon checkbox on the webform settings?

I've pushed a tiny fix for the 'complete form' error you were having earlier. Maybe that'll fix it, but please check you given anon permissions on that particular webform, since looking at the code, it should be fixed by the last psuh.

**Comment by bd0bd** [comment]
**docwilmot**
1. I have reinstalled Backdrop and Webform 30 minutes ago (the latest versions). Now it works fine without adding $form_state['complete form'] = array();
2. Yes, I have checked anon checkboxes but the form is not visible on the page.
   It is visible only in the case if I select **Disable Webform submission access control** in the **Submission access control**.

![permissions](https://cloud.githubusercontent.com/assets/13515302/9156695/210e6bda-3eec-11e5-84a7-ff04310fbe06.gif)

![request](https://cloud.githubusercontent.com/assets/13515302/9156706/377eedb8-3eec-11e5-9452-253cf2a3205b.gif)

**Comment by docwilmot** [comment]
**These settings?**

![these_settings](https://cloud.githubusercontent.com/assets/1042283/9157404/ae562a76-3ec1-11e5-85da-793efb977949.PNG)

**On this page?**

![thispage](https://cloud.githubusercontent.com/assets/1042283/9157405/ae667c8c-3ec1-11e5-97a0-07931d1e97c6.PNG)

**Comment by bd0bd** [comment]
OMG!
Sorry, I did not see this option.
Everything is ok now.
Thank you! :)

**Comment by Graham-72** [comment]
Thanks @biolithic for porting this and @docwilmot for fixing things. Is it now ready for an official release? I would welcome getting it included in updates.

**Comment by biolithic** [comment]
I can include all the fixes and push an official release today or we can
wait for @quicksketch .  I don't want to become the official maintainer for
this project.
